### ISSUE TITLE
Specifying custom library component.

### ISSUE THREAD

**Issue by osresearch** [Blinkinlabs/circuitpainter#1]
In my project I have a `Library.pretty` directory with custom components, but when I try to place them using circuitpainter I get an error:

```
% python3 painter-v2 
Traceback (most recent call last):
  File "painter-v2", line 20, in <module>
    painter.footprint(0,0, "Library", "LED_APHB1608SYKSURKC", nets=[
  File "/home/hudson/.local/lib/python3.8/site-packages/circuitpainter/circuitpainter.py", line 429, in footprint
    raise IOError(
OSError: Footprint LED_APHB1608SYKSURKC in library:/usr/share/kicad/footprints/Library.pretty not found
```

Is there a way to specify the search path to include the local directories?

**Comment by osresearch** [comment]
I see that `library_path` was added as an optional argument to the constructor in https://github.com/Blinkinlabs/circuitpainter/commit/215aa0eb093c5c1c1187a3ce3f373a822ac6bf41
