### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'FootprintLoad'

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/circuitpainter#7]
Attempting to run an example with KiCad 8 gives the following error:

C:\Users\matt\repos\circuitpainter\examples>python hello_painter.py
Traceback (most recent call last):
  File "C:\Users\matt\repos\circuitpainter\examples\hello_painter.py", line 11, in <module>
    painter.footprint(0,0,"Resistor_SMD","R_0805_2012Metric",nets=['gnd',f'led_{angle}'])
  File "C:\Users\matt\repos\circuitpainter\src\circuitpainter\circuitpainter.py", line 487, in footprint
    footprint = pcbnew.FootprintLoad(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\pcbnew.py", line 19081, in FootprintLoad
    return plug.FootprintLoad(libname,name,preserveUUID)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'FootprintLoad'

**Comment by cibomahto** [comment]
This is caused by an incorrect path to the KiCad library on Windows. In [_guess_footprint_library_path()](https://github.com/Blinkinlabs/circuitpainter/blob/a110b9e08b63c81682fda9efc9f9619f749027bb/src/circuitpainter/circuitpainter.py#L21), it is hardcoded to use the KiCad 7 library.

Changing it to 8 causes this to work, but is not a robust solution.
